openapi: 3.0.0
info:
  title: seisankun_api_v2
  version: '1.0'
  description: 旅の立て替え清算を管理してくれる「清算くん」のバックエンドAPI
  contact:
    name: nooboolean
    url: 'https://twitter.com/nooboolean'
  termsOfService: 'https://seisan-kun.netlify.app/#/tos'
servers:
  - url: 'http://localhost:3000'
    description: Dev
  - description: Staging
    url: 'https://stg-seisan-kun-api-v2.herokuapp.com'
  - url: 'https://prd-seisan-kun-api-v2.com'
    description: Production
paths:
  /travel:
    get:
      description: 旅行の情報と、参加メンバーを参照するAPI
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  travel:
                    $ref: '#/components/schemas/Travel'
                  members:
                    type: array
                    items:
                      $ref: '#/components/schemas/Member'
              examples:
                example-1:
                  value:
                    travel:
                      id: 1
                      name: 温泉旅行
                      travel_key: aaabbbcccddd
                      created_at: '2021-01-01T01:01:01Z'
                      updated_at: '2021-01-01T01:01:01Z'
                    members:
                      - id: 1
                        name: nooboolean
                        created_at: '2021-01-01T01:01:01Z'
                        updated_at: '2021-01-01T01:01:01Z'
                      - id: 2
                        name: Jump 半在
                        created_at: '2021-01-01T01:01:01Z'
                        updated_at: '2021-01-01T01:01:01Z'
                      - id: 3
                        name: nakazaway
                        created_at: '2021-01-01T01:01:01Z'
                        updated_at: '2021-01-01T01:01:01Z'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      operationId: get-travel
      parameters:
        - schema:
            type: string
          in: query
          name: travel_key
          description: 旅行を一意に表すkey
          required: true
    parameters: []
    post:
      summary: ''
      tags: []
      operationId: post-travel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  travel_key:
                    type: string
                required:
                  - travel_key
              examples:
                example-1:
                  value:
                    travel_key: aaaabbbbccccdddd
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      description: 旅行を新規作成するAPI
      requestBody:
        $ref: '#/components/requestBodies/TravelRegisterRequest'
    put:
      summary: ''
      tags: []
      operationId: put-travel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  travel_key:
                    type: string
              examples:
                example-1:
                  value:
                    travel_key: aaabbbccccdddd
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      description: 指定した旅行の情報を更新するAPI
      requestBody:
        $ref: '#/components/requestBodies/TravelUpdateRequest'
    delete:
      summary: ''
      tags: []
      operationId: delete-travel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                example-1:
                  value:
                    message: success
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      description: 指定した旅行の情報を削除するAPI
      parameters:
        - schema:
            type: string
          in: query
          name: travel_key
          description: 旅行を一意に表すkey
          required: true
  /payment/history:
    get:
      description: 指定した旅行の支払い情報をすべて参照するAPI
      summary: ''
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/PaymentHistories'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      operationId: get-payment-history
      parameters:
        - schema:
            type: string
          in: query
          name: travel_key
          description: 旅行を一意に表すkey
          required: true
    parameters: []
  /payment:
    get:
      description: 指定した支払いの情報を参照するAPI
      summary: ''
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/Payment'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      operationId: get-payment
      parameters:
        - schema:
            type: string
          in: query
          name: payment_id
          description: 支払い情報のid
          required: true
    parameters: []
    post:
      summary: ''
      tags: []
      operationId: post-payment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  payment_id:
                    type: integer
                required:
                  - payment_id
              examples:
                example-1:
                  value:
                    payment_id: 1
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      description: 支払いを追加するAPI
      requestBody:
        $ref: '#/components/requestBodies/PaymentRegisterRequest'
    put:
      summary: ''
      tags: []
      operationId: put-payment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  payment_id:
                    type: integer
              examples:
                example-1:
                  value:
                    payment_id: 1
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      description: 指定した支払いの情報を更新するAPI
      requestBody:
        $ref: '#/components/requestBodies/PaymentUpdateRequest'
    delete:
      summary: ''
      tags: []
      operationId: delete-payment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                example-1:
                  value:
                    message: success
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      description: 指定した支払いの情報を削除するAPI
      parameters:
        - schema:
            type: string
          in: query
          name: payment_id
          description: paymentのID
          required: true
  /calculation/results:
    get:
      description: 指定した旅行の清算結果をすべて参照するAPI
      summary: ''
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/CalcResults'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      operationId: get-calculation-results
      parameters:
        - schema:
            type: string
          in: query
          name: travel_key
          description: 旅行を一意に表すkey
          required: true
    parameters: []
  /borrowing/history:
    parameters: []
    get:
      description: 指定したメンバーの貸借履歴をすべて参照するAPI
      summary: ''
      tags: []
      operationId: get-borrowing-history
      responses:
        '200':
          $ref: '#/components/responses/BorrowHistories'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      parameters:
        - schema:
            type: integer
          in: query
          name: member_id
          description: メンバーのid
          required: true
  /borrowing/statuses:
    get:
      description: 指定した旅行の貸借状況をすべて参照するAPI
      summary: ''
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/BorrowStatuses'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      operationId: get-borrowing-statuses
      parameters:
        - schema:
            type: string
          in: query
          name: travel_key
          description: 旅行を一意に表すkey
          required: true
    parameters: []
  /member:
    parameters: []
    post:
      description: メンバーを追加するAPI
      summary: ''
      tags: []
      operationId: post-member
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  member_id:
                    type: integer
                required:
                  - member_id
              examples:
                example-1:
                  value:
                    member_id: 1
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      requestBody:
        $ref: '#/components/requestBodies/MemberInsertRequest'
    delete:
      summary: ''
      tags: []
      operationId: delete-member
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                example-1:
                  value:
                    message: success
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
        '502':
          $ref: '#/components/responses/Error'
        '503':
          $ref: '#/components/responses/Error'
      description: 指定したメンバーを旅行から削除するAPI
      parameters:
        - schema:
            type: string
          in: query
          name: member_id
          description: memberのID
          required: true
components:
  schemas:
    Travel:
      title: Travel
      type: object
      description: ''
      x-internal: false
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        travel_key:
          type: string
        name:
          type: string
        created_at:
          type: string
          description: Set to true if the user's email has been verified.
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          description: The date that the user was created.
          readOnly: true
      required:
        - id
        - travel_key
        - name
        - created_at
        - updated_at
      x-examples:
        example-1:
          id: 1
          travel_key: aaaabbbbccccdddd
          name: 温泉旅行
          created_at: '2021-01-01T01:01:01Z'
          updated_at: '2021-01-01T01:01:01Z'
    Member:
      title: Member
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - id
        - name
        - created_at
        - updated_at
      x-examples:
        example-1:
          id: 1
          name: nooboolean
          created_at: '2021-01-01T01:01:01Z'
          updated_at: '2021-01-01T01:01:01Z'
  requestBodies:
    TravelRegisterRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              members:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
              travel:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
            required:
              - members
              - travel
          examples:
            example-1:
              value:
                members:
                  - name: nooboolean
                  - name: Jump 半在
                  - name: nakazaway
                travel:
                  name: 温泉旅行
        application/xml:
          schema:
            type: object
            properties: {}
      description: ''
    PaymentRegisterRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              payment:
                type: object
                properties:
                  travel_key:
                    type: string
                  payer_id:
                    type: integer
                  borrowers:
                    type: array
                    items:
                      type: object
                      properties:
                        borrower_id:
                          type: integer
                  title:
                    type: string
                  amount:
                    type: integer
          examples:
            example-1:
              value:
                payment:
                  travel_key: aaabbbcccddd
                  payer_id: 1
                  borrowers:
                    - borrower_id: 1
                    - borrower_id: 2
                  title: 高速代
                  amount: 3000
    TravelUpdateRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              travel:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
            required:
              - travel
          examples:
            example-1:
              value:
                travel:
                  id: 1
                  name: 九州旅行
    PaymentUpdateRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              payment:
                type: object
                properties:
                  id:
                    type: integer
                  travel_key:
                    type: string
                  payer_id:
                    type: integer
                  borrowers:
                    type: array
                    items:
                      type: object
                      properties:
                        borrower_id:
                          type: integer
                  title:
                    type: string
                  amount:
                    type: integer
            required:
              - payment
          examples:
            example-1:
              value:
                payment:
                  id: 1
                  travel_key: aaaabbbbccccdddd
                  payer_id: 1
                  borrowers:
                    - borrower_id: 1
                    - borrower_id: 2
                  title: ホテル代
                  amount: 10000
    MemberInsertRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              travel:
                type: object
                properties:
                  travel_key:
                    type: string
              member:
                type: object
                properties:
                  name:
                    type: string
          examples:
            example-1:
              value:
                travel:
                  travel_key: aaaabbbbccccdddd
                member:
                  name: Jump 半在
  responses:
    BorrowStatuses:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              statuses:
                type: array
                items:
                  type: object
                  properties:
                    member:
                      $ref: '#/components/schemas/Member'
                    lend_borrow_money:
                      type: number
          examples:
            example-1:
              value:
                statuses:
                  - member:
                      id: 1
                      name: nooboolean
                      created_at: '2021-01-01T01:01:01Z'
                      updated_at: '2021-01-01T01:01:01Z'
                    lend_borrow_money: 100.989
                  - member:
                      id: 2
                      name: Jump 半在
                      created_at: '2021-01-01T01:01:01Z'
                      updated_at: '2021-01-01T01:01:01Z'
                    lend_borrow_money: 1231.566
                  - member:
                      id: 3
                      name: nakazaway
                      created_at: '2021-01-01T01:01:01Z'
                      updated_at: '2021-01-01T01:01:01Z'
                    lend_borrow_money: -12312.098
    BorrowHistories:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              lend_histories:
                type: array
                items:
                  type: object
                  properties:
                    lend:
                      type: object
                      properties:
                        title:
                          type: string
                        money:
                          type: number
                        payment_id:
                          type: integer
                    payer:
                      type: object
                      properties:
                        name:
                          type: string
              borrow_histories:
                type: array
                items:
                  type: object
                  properties:
                    borrow:
                      type: object
                      properties:
                        title:
                          type: string
                        money:
                          type: number
                        payment_id:
                          type: integer
                    payer:
                      type: object
                      properties:
                        name:
                          type: string
          examples:
            example-1:
              value:
                lend_histories:
                  - lend:
                      title: ホテル代
                      money: 10000
                      payment_id: 123
                    payer:
                      name: Jump　半在
                borrow_histories:
                  - borrow:
                      title: 高速代
                      money: 333.333
                      payment_id: 124
                    payer:
                      name: nakazaway
                  - borrow:
                      title: 夜飯代
                      money: 1029.234
                      payment_id: 125
                    payer:
                      name: yseki
    CalcResults:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  type: object
                  properties:
                    borrower_name:
                      type: string
                    lender_name:
                      type: string
                    borrow_money:
                      type: number
          examples:
            example-1:
              value:
                results:
                  - borrower_name: Jump 半在
                    lender_name: nooboolean
                    borrow_money: 1000
                  - borrower_name: Jump 半在
                    lender_name: nakazaway
                    borrow_money: 3000.897
    Error:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  message:
                    type: string
          examples:
            example-1:
              value:
                error:
                  message: string
    PaymentHistories:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              payments:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    travel_key:
                      type: string
                    payer_id:
                      type: integer
                    payer_name:
                      type: string
                    title:
                      type: string
                    amount:
                      type: integer
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
          examples:
            example-1:
              value:
                payments:
                  - id: 1
                    travel_key: aaabbbcccddd
                    payer_id: 1
                    payer_name: Jump 半在
                    title: 高速代
                    amount: 3000
                    created_at: '2021-01-01T01:01:01Z'
                    updated_at: '2021-01-01T01:01:01Z'
    Payment:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              payment:
                type: object
                properties:
                  id:
                    type: integer
                  travel_key:
                    type: string
                  payer_id:
                    type: integer
                  borrowers:
                    type: array
                    items:
                      type: object
                      properties:
                        borrower_id:
                          type: integer
                        borrower_name:
                          type: string
                  title:
                    type: string
                  amount:
                    type: integer
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
          examples:
            example-1:
              value:
                payment:
                  id: 1
                  travel_key: aaaabbbbccccdddd
                  payer_id: 1
                  borrowers:
                    - borrower_id: 1
                      borrower_name: Jump 半在
                  title: 高速代
                  amount: 3000
                  created_at: '2021-01-01T01:01:01Z'
                  updated_at: '2021-01-01T01:01:01Z'
